wagtail/wagtail.org

- wagtailio/core/templates/core/includes/contact_torchbox.html
Changes the link to 'Contact Torchbox' to the wagtail cms page (which has an enquiries link), rather than to the general torchbox contact form.
> Amend link target for 'Contact the creators'

- wagtailio/blog/models.py
- wagtailio/core/models.py
- wagtailio/utils/models.py
Restricted a few child page types. Threw in a quick help_text typo fix.
> Restrict page hierarchy

- wagtailio/static/css/core/blog.scss
* Note: quick fix
* due to the long list of blog posts, -200% is not enough to 'hide' all the blog listing
* ideally the blog listing should be completely hidden on mobile, however, display: none causes some flickering of the menu on scrolling
> update blog.scss - ensure menu hides on sm devices

- wagtailio/utils/templatetags/wagtailio_utils.py
I was spinning up the Vagrant box and ran into this, thought I'd catch the `DoesNotExist` exception so the base.html template will render even without a menu.
> Primary MenuSnippet Exception

- requirements.txt
Upgrading Wagtail to v2.3. I recall some Django version issues around this time, so I pinned Django to 2.1.13 and will update Django as Wagtail gets updated. 
There was a Pillow warning. Pillow 6.2.0 was being installed but `<6.0` was required for Wagtail 2.3, so I pinned the latest accepted version of Pillow which was `5.4.1`.
Running the site locally seemed to work fine for me, but I'm not sure if there's a preferred way to test a production-like site just to check. It'd be great if someone else could also make sure the requirements don't break wagtail.io before deploying.
> Version bumps: Django 2.1.13, Wagtail 2.3, Pillow 5.4.1

- .gitignore
- heroku.yml
This fixes #28 
Migrations were not being run because Heroku apparently only accepts a single release command entry anymore. Not sure why but with this fix it should be working again!
> Fix migrate command on release

- wagtailio/blog/templates/blog/blog_page.html
- wagtailio/static/css/components/blog.scss
- wagtailio/static/css/components/nav-item.scss
- wagtailio/static/css/components/page_content.scss
This PR adds/fixes: 
- underline for links to make them more recognisable as links. Similar to the look of torchbox.com.
- Remove mobile menu font weight and uppercasing.
- Fix mobile menu documentation icon not visible against background.
> Fix link appearance to be more recognisable. Mobile menu fixes.

- wagtailio/newsletter/templates/newsletter/newsletter_page.html
This fixes #2
I have made the headings and links slightly darker to provide enough contrast on the white background.
Link colors now pass WCAG AA where they previously did not.
> A11Y improvements on newsletter page

- wagtailio/static/css/core/base.scss
This fixes #26.
With this PR inline code blocks now look like this:
> Add styling for inline code blocks

- requirements.txt
- wagtailio/core/wagtail_hooks.py
This pull request will upgrade Wagtail to the latest 2.8 release.
- Django was upgraded to 2.2.10 to fix a recent security vulnerability.
- django-basic-auth-ip-whitelist was also upgraded to fix a compatibility warning with Django.
- In Wagtail 2.8 `get_document_model()` was moved. https://docs.wagtail.io/en/v2.8/releases/2.8.html#wagtail-documents-models-get-document-model-has-moved.
The upgrade process was very smooth. Kudos Wagtail developers 👌
> Upgrade Wagtail to 2.8 and Django to 2.2.10 LTS

- wagtailio/templates/base.html
Fixes #51
The intro is truncated to 160 chars for meta description and 200 for og:description as those seem to be the max recommended values based on my research.
> Add blog post main image/intro as fallbacks for meta desc/image

- wagtailio/blog/models.py
- wagtailio/features/models.py
- wagtailio/settings/base.py
Blog pages can sit outside blog section so slug is not actually guaranteed unique - eg with current data the slug 'test' is not unique so will cause problems.
> Use Wagtail ID as the unique field for airtable mapping

- wagtailio/templates/404.html
Otherwise it just shows the title suffix, and starting with a `|`  looks unintentional
> Add page title to 404 page

- requirements.txt
- wagtailio/settings/base.py
We want to be able to test wagtail-ab-testing a bit more, and maybe run some tests on the wagtail.io site for fun. So I added the wagtail a/b testing package to the site. Tested on a fresh install and it works out of the box.
> Add A/B testing

- README.md
- conf/wagtaildocs-cloudflare-worker.js
Not specifically related to this codebase, but added here to keep it safe...
This is the cloudflare worker used on docs.wagtail.io to rewrite `<link rel="canonical">` URLs in old versions of the docs to point to the 'stable' branch, to hopefully ensure that Google is indexing up-to-date versions of the docs.
> docs.wagtail.io cloudflare worker script

- wagtailio/static/css/components/nav-item.scss
Fixes the visible flicker on homepage (on hover) and removes the border from the overlay menu as the whole item background colour changes. Follow up from #109
> Fix nav border flicker

- wagtailio/static/css/components/base.scss
This tweak makes videos embedded with the <video> tag adjust their width to the size of the screen.
> Make videos responsive

- wagtailio/static/js/main.js
* Ensure that when users click the 'close' button on the cookies message it does not scroll to the top
* As the button is a link, when clicked it will go to the `href='#'` which will move the user to the stop
* Prevent this action using event.preventDefault
* Note: I only tested manually in the browser (using jquery), not by building the site locally
Screenshot of issue (note the href="#").
> Stop scroll to top on cookies close button

- wagtailio/templates/base.html
This is currently breaking sharing images on Twitter, e.g. from https://wagtail.io/blog/wordpress-to-wagtail-migration-kit/:
```
<meta name="twitter:image" content="https://media.wagtail.io/images/WP_to_Wagtail_Blog_Image.width-400.png
" />
```
> Remove whitespace from Twitter image URL

- vagrant/provision.sh
The production and staging environments for wagtail.io run on postgres 13.5. However the development environment hasn't been updated accordingly.
This PR fixes that. Thanks @kaedroho for your guidance.
> Upgrade postgres in development environment

- conf/wagtaildocs-cloudflare-worker.js
As a part of https://github.com/wagtail/wagtail/issues/7841, we need to update this worker to correct rewrite using the new domain.
See also https://github.com/wagtail/wagtail/pull/7846
> Update docs URL rewriter to use new .org domain

- wagtailio/static/css/components/alert.scss
- wagtailio/static/css/components/header.scss
- wagtailio/static/js/main.js
- wagtailio/templates/base.html
#147 with extra front-end tweaks. The alert itself looks the same, I just fixed the issues I reported in #147, fixed the animation, and moved it to be above the header.
If we want to move it below the header again, it’s just a matter of moving the element back to where it was before.
> Remove the need for relative positioning causing layout issues

- wagtailio/api.py
**Context**
We want to query data from the AreWeHeadlessYet site using the API. However, we can't use the `areweheadlessyet.wagtail.org` domain for the  AreWeHeadlessYet site/backend because it's already used for the Next.js frontend hosted in Vercel.
**Solution**
Use the `wagtail.org` domain to serve content from the AreWeHeadlessYet site/backend - that is the goal of this PR.
> Modify the API to serve content from AreWeHeadlessYet site

- wagtailio/areweheadlessyet/signal_handlers.py
- wagtailio/areweheadlessyet/thread_pool.py
We were having an issue with the automatic deploy hook as it seemed that the signal listeners 'weren't listening'.
This happened because the `deploy` function was defined inside another function. Thus, no other part of the program references it once that function is run. However, signal listeners are weakly referenced hence the 'bug'.
I changed the `deploy` function to be a global one.
> Move deploy signal handler outside function to avoid it being garbage collected

- .github/workflows/ci.yml
This picks up from 2190d16c41a3e7b628ab831795150135957a2c98 and adds an additional backend job which, for now
- runs system checks
- checks for missing migrations
- runs test suite
Future:
- add linting (black, flake8, isort)
> Add python test job to GitHub Actions

- wagtailio/project_styleguide/templates/patterns/components/streamfields/quotes/standalone_quote_block.html
- wagtailio/project_styleguide/templates/patterns/components/streamfields/quotes/standalone_quote_block.yaml
- wagtailio/static/sass/base/_typography.scss
- wagtailio/static/sass/components/_standalone-quote.scss
- wagtailio/static/sass/main.scss
Adds the FE for standalone quote component viewable [in the pattern library here](http://localhost:8000/pattern-library/render-pattern/patterns/components/streamfields/quotes/standalone_quote_block.html). The icon will need refactoring once https://github.com/wagtail/wagtail.org/pull/195 is in.
Also:
- Fixes font size of `mini-meta` above large breakpoint. It should be 14px across all breakpoints.
> Standalone Quote

- wagtailio/static/sass/components/_logo-card.scss
Ensure the logo appears at the same point regardless of how much text each card has
> Logo card alignment

- wagtailio/project_styleguide/templates/patterns/_pattern_library_only/rich_text_example.html
- wagtailio/project_styleguide/templates/patterns/pages/blog/blog_page.html
- wagtailio/project_styleguide/templates/patterns/pages/blog/blog_page.yaml
- wagtailio/static/sass/components/_blog.scss
Spotted a couple of bugs on the blog page:
- Remove wrapping blog content class as the SF's used on the page have their own grid class
- Fixes author image on blog page
- Adds grid class to rich text example template
> Blog page fixes

- wagtailio/project_styleguide/templates/patterns/components/streamfields/content_story_block.html
This is a fix to ensure that the _get started_ block in the **ContentPage**'s body StreamField actually renders when it is included. 
Prior to this, the block did not render
> Fix broken rendering of 'get started' block on Content page template

- wagtailio/project_styleguide/templates/patterns/components/meta/meta.html
- wagtailio/project_styleguide/templates/patterns/components/related-content/related-content.html
- wagtailio/project_styleguide/templates/patterns/components/streamfields/cards/logo_card_block.html
- wagtailio/project_styleguide/templates/patterns/components/streamfields/cards/related_page_card_block.html
- wagtailio/project_styleguide/templates/patterns/components/streamfields/cards/related_page_card_block.yaml
This MR picks up from #222, and provides a fix to ensure that related pages are displayed on a blog page.
Details of the fix
1. Instead of using [logo_card_block.html](https://github.com/wagtail/wagtail.org/blob/ce622774084d59d669ed8a49adee0839312d7488/wagtailio/project_styleguide/templates/patterns/components/streamfields/cards/logo_card_block.html) as the template, create a new template [related_page_card_block.html](https://github.com/wagtail/wagtail.org/blob/16f8719fbaaf6b974867e7d4aa2f3f0b9133ea9d/wagtailio/project_styleguide/templates/patterns/components/streamfields/cards/related_page_card_block.html), which is essentially a copy of the former, but with updated field names to match the **BlogPage** model.
2. Fix `value` in …
> Fix rendering of related pages on blog page

- wagtailio/static/sass/components/_comparison-table.scss
This tweak forces the table "categories" to maintain their sizing regardless of large images being added.
> Comparison table column fix

- wagtailio/project_styleguide/templates/patterns/components/hero/hero.html
Add missing class to hero button so it's hidden on the feature index page
> Hide CTA in feature index hero

- requirements.txt
- wagtailio/settings/base.py
Related to #5 
set up the `Strict-Transport-Security` (HSTS), `Content-Security-Policy` (CSP), and `Permissions-Policy` headers.
- tweak some existing config:
- Force `SECURE_SSL_REDIRECT` as true always
- Set up a default value of 30 days for `SECURE_HSTS_SECONDS`
- use `django-csp` and environment variables for CSP headers, and
- use `django-permissions-policy` for Permissions Policy headers.
- I've set most of the features as disabled because it doesn't look like we need them for wagtail.org (except `fullscreen` which I left out so that we can still use full screen with youtube videos)
> Add config for security headers

- wagtailio/core/models/mixins.py
- wagtailio/project_styleguide/templates/patterns/pages/content_page/content_page.html
- wagtailio/project_styleguide/templates/patterns/pages/content_page/content_page.yaml
This is a simple approach to not display the hero on content_page templates that do not supply hero variables.
> Add property to hide hero

- wagtailio/newsletter/templates/newsletter/newsletter_index_page.html
An attempt to consolidate Mailchimp lists for our Wagtail Newsletters went awry and I needed to recreate the list. I've updated the embedded form in the newsletter index page template to include the new audience ids.
I realized a bit belatedly that I could have just switched out the audience ids rather that replacing the whole form. So the code formatting is a bit different now. I'll correct anything that fails the style check, but if there is anything else that needs to be fixed, please let me know.
> Updated embedded Mailchimp form to reflect new list ID

- wagtailio/settings/base.py
In addition to #264, this PR adds [`BASIC_AUTH_WHITELISTED_PATHS`](https://github.com/tm-kn/django-basic-auth-ip-whitelist#basic_auth_whitelisted_paths) to the django-basic-auth-ip-whitelist configuration.
> Add BASIC_AUTH_WHITELISTED_PATHS to django-basic-auth-ip-whitelist configuration

- docker-compose.yml
fixes the healthcheck command, and changes the use of `wagtailio` to `wagtailorg` where possible
> Docker compose update

- wagtailio/blog/models.py
- wagtailio/core/models/pages.py
- wagtailio/developers/models.py
- wagtailio/features/models.py
- wagtailio/newsletter/models.py
- wagtailio/packages/models.py
- wagtailio/services/models.py
- wagtailio/standardpage/models.py
This PR updates `Page` models by adding fields to the `search_fields` property, in order for us to be able to search on them. See below for details of the Page models and fields added (in addition to `Page.search_fields`):
**BlogPage**
- introduction
- body
**HomePage**
- heading
- sub_heading
- intro
- body
**ContentPage**
- heading
- sub_heading
- intro
- body
**DevelopersPage**
- body
**FeatureIndexPage**
- subheading
- features
**NewsletterPage**
- intro
- body
**NewsletterIndexPage**
- intro
- body
**PackagesPage**
- subtitle
- about_title
- about_text
**ServicesPage**
- intro
- body
**StandardPage**
- introduction
- body
---
Monday reference: [#96](https://torchbox.monday.com/boards/1123315381/pulses/1130743612)
> Search index fields

- wagtailio/navigation/models.py
- wagtailio/project_styleguide/templates/patterns/includes/menu_footer.html
- wagtailio/project_styleguide/templates/patterns/includes/menu_main.html
- wagtailio/settings/base.py
Builds on #285 and adds template fragment cache for main and footer nav.
The cache is cleared when the navigation settings is saved. It is also cleared when one saves the main or footer nav snippet that is in use.
Note: using snippets for main/footer nav so as to implement previews now that we are on Wagtail 4
> Nav fragment caching and renditions cache

- wagtailio/core/blocks.py
- wagtailio/project_styleguide/templates/patterns/components/get-started/get-started.html
- wagtailio/project_styleguide/templates/patterns/components/icon-link/icon-link.html
- wagtailio/project_styleguide/templates/patterns/components/nav-cta/nav-cta.html
- wagtailio/project_styleguide/templates/patterns/includes/menu_footer.html
- wagtailio/project_styleguide/templates/patterns/includes/menu_get_started.html
- wagtailio/project_styleguide/templates/patterns/includes/menu_main.html
This PR fixes the links in the "Get started" block, and updates the nav to make use of `pageurl`
> Fix get started block links

- wagtailio/static/sass/components/_modal.scss
This fixes the z-index of the modal to avoid overlapping with the main content. Not sure whether the page is supposed to be scrollable when a modal is open, but I still keep the current behaviour in this PR.
I also don't know whether the modal is supposed to be off-center (a bit slightly to the top), but I made it centered in this PR.
https://user-images.githubusercontent.com/6379424/198681142-31660e9d-bea3-40b6-b672-d5e5ca598ce1.mov
https://user-images.githubusercontent.com/6379424/198682446-ae0749ff-5ba0-4fd5-bef6-5000124fc0d9.mov
> Fix modal positioning and contrast issues

- wagtailio/newsletter/templates/newsletter/newsletter_page.html
- wagtailio/project_styleguide/templates/patterns/base_page.html
Right now the `base_page.html` template only adds the tag if the page has a `canonical_url`, which currently only exists in the `BlogPage` model:
https://github.com/wagtail/wagtail.org/blob/76b2b90c789db002ad2ee5662dcad83871c49dde/wagtailio/blog/models.py#L126-L129
As per our SEO recommendations, we should add this tag sitewide. This PR implements it by falling back to the page's `full_url` if the `canonical_url` field is unset. From a quick look, it seems that all of our pages (except This New in Wagtail newsletter pages) extend the `base_page.html` template, so I think this should cover the whole site.
Templates that extend from `base_page.html` but isn't rendered with a Wagtail `Page` instance, e.g. 500 and 404 pages, will not have the canonical tag.
I handled the …
> Add canonical link tags

- wagtailio/packages/views.py
It is needlessly complex to invert the result of a boolean comparison. The opposite comparison should be made instead.
> Use the 'is not' operator

- wagtailio/project_styleguide/templates/patterns/components/streamfields/features/feature_index_block.html
Each `<fieldset>` element should have a corresponding `<legend>` element to describe what the set of fields is about.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset
Not sure if we'd like to use `{% trans %}` or put it [in the block itself](https://github.com/wagtail/wagtail.org/blob/next/wagtailio/features/blocks.py#L60) (as a `heading`  `CharBlock` maybe). However, the block currently seems to be quite specific to "Features" (instead of being a generic categorised block), so I think it's fine to put it in the template.
> Add `<legend>` element to `<fieldset>` for feature index block

- package-lock.json
- package.json
- wagtailio/project_styleguide/templates/patterns/includes/header.html
- wagtailio/static/js/components/mobile-menu.js
- wagtailio/static/js/components/mobile-sub-menu.js
- wagtailio/static/sass/layout/_header.scss
This PR adds a focus trap to the navigation menu on mobile devices to prevent tabbing outside of the menu and thus focusing on elements that are covered by the menu.
> Implement focus trap on mobile navigation menu

- wagtailio/project_styleguide/templates/patterns/includes/menu_main.html
- wagtailio/project_styleguide/templates/patterns/pages/home/home_page.html
- wagtailio/static/js/components/desktop-close-menus.js
- wagtailio/static/sass/components/_primary-nav.scss
- wagtailio/static/sass/components/_sub-nav.scss
Fixes:
- #304 & #306 (same fix)
- #305
- #307
- #308
- …and one item from our accessibility audit (alt text for the video).
There isn’t that much in common between those issues, just grouping them so it’s easier to test everything in one go.
> Close desktop sub-menus when pressing Esc

- wagtailio/urls.py
- wagtailio/utils/sitemap_generator.py
Since we're only outputting the URL and last modified date (`last_published_at` or `latest_revision_created_at`), we don't need the specific objects
(red - before, green - after)
> Use a slightly more efficient sitemap

- wagtailio/project_styleguide/templates/patterns/includes/footer.html
It’s not appropriate for `aria-label` to contain _less_ content than the equivalent text without it
> Remove extra aria-label from hard-coded footer links

- wagtailio/settings/base.py
This value is currently empty, meaning no additional validation on passwords is done. This adds a few common validators to increase password security.
> Set AUTH_PASSWORD_VALIDATORS

- heroku.yml
- wagtailio/settings/production.py
`python manage.py check --deploy` output with our current setup:
```
WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
?: (security.W016) You have 'django.middleware.csrf.CsrfViewMiddleware' in your MIDDLEWARE, but you have not set CSRF_COOKIE_SECURE to True. Using a secure-only CSRF cookie makes it more difficult for network traffic sniffers …
```
> Use secure cookies for session and CSRF

- wagtailio/utils/views.py
This is an extension and cleanup of #333.
See also https://git.torchbox.com/internal/wagtail-kit/-/blob/master/wagtailkit_repo_name/wagtailkit_repo_name/utils/views.py (Torchbox only)
> Reuse Django's error views for custom views

- wagtailio/static/sass/abstracts/_mixins.scss
- wagtailio/static/sass/components/_backers.scss
- wagtailio/static/sass/components/_card-grid.scss
- wagtailio/static/sass/components/_cta-block.scss
- wagtailio/static/sass/components/_cta.scss
- wagtailio/static/sass/components/_document.scss
- wagtailio/static/sass/components/_embed.scss
- wagtailio/static/sass/components/_features.scss
- wagtailio/static/sass/components/_headline.scss
- wagtailio/static/sass/components/_hero.scss
- wagtailio/static/sass/components/_highlight.scss
- wagtailio/static/sass/components/_icon-bullet.scss
- wagtailio/static/sass/components/_icon-bullets.scss
- wagtailio/static/sass/components/_image.scss
- wagtailio/static/sass/components/_logo-card-grid.scss
- wagtailio/static/sass/components/_logos.scss
- wagtailio/static/sass/components/_pagination.scss
- wagtailio/static/sass/components/_quotes.scss
- wagtailio/static/sass/components/_rich-text.scss
- wagtailio/static/sass/components/_sign-up-form.scss
- wagtailio/static/sass/components/_standalone-quote.scss
- wagtailio/static/sass/components/_text-media.scss
- wagtailio/static/sass/layout/_blog-listing.scss
The spacing between StreamField blocks was too large and making our blog pages look a little funny. I initially removed the media query in `@mixin sf-spacing()` but that broke the spacing around the hero areas and other elements. So I updated `sf-spacing` to include a variable `$multiple` that could be used to adjust spacing for individual elements in multiples of 25px. Then I updated all selectors that use that mixin according to the amount of space needed for each element.
I also removed a media-query the `.icon-bullet` selector since that needed adjustment as well.
Please let me know if there's anything I can do to improve this adjustment to the spacing.
> Updates to the streamfield spacing mixin and subsequent adjustments

- wagtailio/newsletter/templates/newsletter/newsletter_index_page.html
One of the newsletter links was old and needed to be updated to match the current list.
> Updated an old newsletter link to the new list.

- wagtailio/project_styleguide/templates/patterns/components/streamfields/text_and_media_block/text_and_media_block.html
- wagtailio/project_styleguide/templates/patterns/components/streamfields/text_and_media_block/text_and_media_block.yaml
Still in use by `TextAndMediaBlock`. I searched for most of the removed templates in #382, but it looks like I missed this one
> Re-add text_and_media_block template

- wagtailio/static/sass/components/_sign-up-form.scss
> Prevent text being lost behind svg at tablet breakpoints

- wagtailio/static/sass/components/_logo-card.scss
- wagtailio/static/sass/components/_sign-up-form.scss
- Fixes #399 
- Fixes #400
From what I tested, this doesn't seem to interfere with the CSS that was added that caused this bug.
The `text-shadow` added in #397 still works for its intended use case:
The added padding for the `logo-card` image still works too:
> Minor fixes

- README.md
Fixed typo for the word dependencies in the README under the frontend tooling section.
This PR fix is for issue #418
> Fixed typo in readme under frontend tooling

- wagtailio/project_styleguide/templates/patterns/pages/blog/includes/blog_post.html
Issue - #351 
Changes -
- Added featured label with icon on featured blog posts 
Let me know if I need to change the icon or do any other customizations.
> Add featured label on featured blogs. Fix #351

- wagtailio/static/sass/layout/_footer.scss
Fixed text disappearing issue in the footer in light mode. 
This PR fix is for issue #405.
Tested the changes on:
OS: Ubuntu 22.0.4
Browser: Google Chrome Version 117.0.5938.149 (Official Build) (64-bit)
> Fixed Text Disappearing issue in footer light mode. Fix #405

- wagtailio/static/sass/components/_milestone-item.scss
Fixed Disappearing Text on Hover for 'Sponsor This' in Light Mode on the Wagtail Roadmap Page
Fixes:
1. Remove background color
2. Added color to the sponsor text on hover.
This is a PR for issue #428 
@thibaudcolas , could you kindly review it.
> Fixed disappearing text on hover for Sponsor This

- wagtailio/static/sass/layout/_footer.scss
We can set color for SVG elements in two ways: using fill and stroke properties of the style attribute. Know more on [MDN docs](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill).
This is a PR for issue [#440](https://github.com/wagtail/wagtail.org/issues/440)
@thibaudcolas  , I am outreachy applicant. could you kindly review it. I want to move on the other fixes.
> sass code fixes inside footer section: hover over SVG icons effect (Follow us icons)

- Dockerfile
- wagtailio/settings/base.py
This will help with rendition file sizes all across.
Example using the staging site homepage:
Dev note: after deployment, run `django-admin wagtail_update_image_renditions` on prod
> Install and enable image optimizer binaries

- wagtailio/search/views.py
Untested. See [5.0 release notes](https://docs.wagtail.org/en/stable/releases/5.0.html#wagtailsearch-query-has-moved-to-wagtail-contrib-search-promotions). Looking into this as part of a 500 error, but I have no idea if it’s enough:
```
File "/app/wagtailio/search/views.py", line 22, in search
promoted_page_pks = query.editors_picks.all().values_list("page__pk", flat=True)
^^^^^^^^^^^^^^^^^^^
AttributeError: 'Query' object has no attribute 'editors_picks'
```
> Update import path for promoted search Query model

- wagtailio/utils/views.py
Untested, just going by [the docs](https://docs.djangoproject.com/en/5.0/ref/views/#the-500-server-error-view). The exception:
```
File "/app/wagtailio/utils/views.py", line 28, in error_500
return defaults.server_error(request, template="patterns/pages/errors/500.html")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[…]
TypeError: server_error() got an unexpected keyword argument 'template'
```
> Fix TypeError in 500 error handling

- wagtailio/static/sass/components/_cta.scss
- wagtailio/static/sass/components/_nav-cta.scss
- wagtailio/static/sass/components/_theme-toggle.scss
- wagtailio/static/sass/layout/_footer.scss
- wagtailio/static/sass/vendor/_code-highlighting.scss
#454
This pull request addresses styling issues related to windows high contrast mode. The following issues have been fixed:
- **CTA button:** 
- Arrow icon isn't visible when hovered.
- Inconsistent transition speeds between the title and subtitle.
- **Header navigation:** Arrow icon within CTA link in sub-navigation panel isn’t visible.
- **Code snippet block:** Code blocks should have a clear separation from regular content.
- **Footer:** 
- All social media, “sponsor Wagtail”, and “contribute code” icons aren't visible. 
- Social media icons are not using the correct color (link text). 
_Note_ - Dark/light mode theme toggle was meant to not be displayed in HCM but used `prefers-contrast` instead of `forced-colors` active.
<details>
<summary>Screenshots</summary>
| | | |
| --- | --- | …
> WHCM styles improvements

- wagtailio/settings/base.py
Due to the default Wagtail behavior of converting avif and webp files to PNGs, we need these settings to allow for these newer and greener file formats to be used on Wagtail.org.
I have decided that will not support GIFs as they tend to be large, unwieldy files and they are a potential source of chaos if animated versions are allowed to be uploaded.
> Updating the image settings to allow avif and webp image formats.

- docker-compose.yml
- wagtailio/areweheadlessyet/fields.py
- wagtailio/areweheadlessyet/models.py
This PR adds the social fields in the API representation of a model.
> Add social fields to API meta fields and add serializer for social image

- wagtailio/newsletter/templates/newsletter/newsletter_page.html
- wagtailio/project_styleguide/templates/patterns/pages/errors/500.html
> style: changed font-size units from px to rem

- wagtailio/project_styleguide/templates/patterns/components/hero/hero.html
- wagtailio/project_styleguide/templates/patterns/components/icon-link/icon-link.html
- wagtailio/project_styleguide/templates/patterns/components/sign_up_form/base_form.html
- wagtailio/project_styleguide/templates/patterns/components/streamfields/headline/headline.html
- wagtailio/project_styleguide/templates/patterns/includes/menu_get_started.html
- wagtailio/project_styleguide/templates/patterns/includes/search-form.html
- wagtailio/static/sass/base/_typography.scss
- wagtailio/static/sass/components/_headline.scss
- wagtailio/static/sass/components/_search.scss
- wagtailio/static/sass/components/_sign-up-form.scss
This PR addresses accessibility issues related to heading levels and forms:
- Fixed instances (in hero, headline, and icon-link blocks) where headings were used consecutively after one another.
- Changed menu_get_started to use an `h2`
- #457
- #459
- Currently screen reader announces sign up forms on the site with "Enter your email address" repeated 3 times. Fixed by changing base_form to use `aria-label="Email"` instead of `<label>`
- Changes the use of `fieldset` in search-form to a `div` (fieldset is used to group multiple form fields together, but there's only one here)
<details>
<summary>Screenshots</summary>
| before | after |
| --- | --- |
|![Screenshot (109)](https://github.com/wagtail/wagtail.org/assets/106587342/fc15bf10-9c86-4492-b8e9-8be0b6bdd35c)|![Screenshot …
> Headings and forms accessibility improvements

- wagtailio/static/sass/base/_print.scss
- wagtailio/static/sass/components/_burger.scss
- wagtailio/static/sass/components/_buttons.scss
- wagtailio/static/sass/components/_code-snippet.scss
- wagtailio/static/sass/components/_modal.scss
- wagtailio/static/sass/components/_theme-toggle.scss
- wagtailio/static/sass/main.scss
This PR addresses styling issues related to print stylesheets and windows high contrast mode:
**Print stylesheets**
- Components with dark backgrounds arent rendered correctly in print. The text appears gray instead of black. 
- Interactive content such as header navigation elements (search, menu toggle), sign-up forms, and videos should be hidden for print.
- In-line href attributes should be used in print so that users are aware of destination of each link.
- Only important iconography and images should be retained for print.
Most site visitors would likely want to print or save blog posts as PDFs compared to other pages on the site. You can see the difference between the blog post [without print styles](https://drive.google.com/file/d/1cRyr8Z1enN4A5GoXRThyD6grKTP-qkJn/view?usp=sharing) …
> Print stylesheets and WHCM improvements

- wagtailio/project_styleguide/templates/patterns/components/streamfields/code_block/code_block.html
- wagtailio/static/sass/abstracts/_mixins.scss
- wagtailio/static/sass/components/_code-block.scss
- wagtailio/static/sass/components/_rich-text.scss
- wagtailio/static/sass/main.scss
- wagtailio/static/sass/vendor/_code-highlighting.scss
This MR will:
1. Apply the same rich text styles applied to `RichTextBlock` to `MarkDownBlock`, which fixes display issues of `ul` and makes other elements display consistently within `MarkDownBlock`s.
2. Standardise the spacing of code blocks within `MarkDownBlock` and `CodeBlock`
Both "Before" and "After" screenshots below are taken using the same StreamField which uses two approaches to achieve the same content:
> Apply richtext styles to markdown blocks and improve spacing of markdown/code blocks

- wagtailio/static/sass/base/_typography.scss
Issue: https://github.com/wagtail/wagtail.org/issues/412
Reduces the sizes of the base h1 and h2 tags above the large breakpoint and does the same for the `.intro-big` class.
Also reduce the bottom margin on all base heading tags.
Updated to units provided by Ben here: https://github.com/wagtail/wagtail.org/issues/412#issuecomment-2147570850
> Update typography sizes and reduce spacing

- wagtailio/static/sass/abstracts/_mixins.scss
This MR removes the bottom margin from the last element (`:last-child`) of rich text elements so that we rely on the parent block's spacing rather than that _plus_ whatever margin exists on the last element.
The example below removes the bottom margin from the `ul`.
**Before:**
**After:**
> Remove surplus margin from richtext elements

- wagtailio/images/views.py
Fixing the issue in PR #504
This query will return correct image usage count, identical to the counts in image edit page.
> Corrected image usage count query

- wagtailio/images/views.py
- wagtailio/images/wagtail_hooks.py
This is a report for identifying images that are not currently in use. Right now it is very basic - a list of all images on the site and a count of how often they are used. There are links to the image usage page and to the image edit where one can delete the image. It is usuable in its current condition but if anyone wants to extend this report, it might be useful to add a FilterSet that allows filtering by collection and/or by used / not used.
> Added an image usage report

- wagtailio/project_styleguide/templates/patterns/components/streamfields/sponsor_block/sponsor_block.html
Follow-up to #530. In addition we should also ideally not be using `ImageBlock`, as it’s mandatory for all images to have alt text in this context (otherwise screen reader users can’t know who the sponsors are).
> Fix sponsor links when there is no link
