wagtail/wagtail.org

app.json, fabfile.py, vagrant/provision.sh
We've moved the staging environment for wagtail.io to Heroku - this MR removes references to the old Dokku environment and updates the `fabfile` to support deploying to Heroku staging.
=> Switch staging environment to Heroku

wagtailio/blog/apps.py, wagtailio/blog/feeds.py, wagtailio/blog/models.py, wagtailio/context_processors.py, wagtailio/core/blocks.py, wagtailio/core/models.py, wagtailio/core/wagtail_hooks.py, wagtailio/developers/apps.py, wagtailio/developers/models.py, wagtailio/features/apps.py, wagtailio/features/blocks.py, wagtailio/features/models.py, wagtailio/images/models.py, wagtailio/newsletter/apps.py, wagtailio/newsletter/models.py, wagtailio/newsletter/views.py, wagtailio/settings/base.py, wagtailio/settings/dev.py, wagtailio/settings/production.py, wagtailio/standardpage/apps.py, wagtailio/standardpage/models.py, wagtailio/urls.py, wagtailio/utils/blocks.py, wagtailio/utils/cache.py, wagtailio/utils/models.py, wagtailio/utils/templatetags/wagtailio_utils.py, wagtailio/utils/views.py
PR for Issue #20 
Seeing as there's only one open PR right now and it only have 2 slightly modified Python files, I thought this would be a good time to run `black`.
Ran `black wagtailio/ --exclude /migrations/` from the source directory. Didn't bother running black on the migration files though. Although we can `black` those files too if someone feels like it's a good idea (I can't imagine people are modifying the existing migration files, but I could be wrong!)
=> Black formatting

wagtailio/newsletter/feeds.py, wagtailio/templates/base.html, wagtailio/urls.py
This fixes #10 
Feedback appreciated
=> Add newsletter RSS feed

requirements.txt, wagtailio/settings/base.py
@tomdyson already added the required credentials added as environment variables to the production server
=> Add Wagtail Alt Generator

wagtailio/blog/models.py
Builds  on #54 
PR opened for reference
=> Enable mapping for blog posts

requirements.txt, wagtailio/newsletter/templates/newsletter/newsletter_page.html, wagtailio/settings/base.py, wagtailio/templates/base.html
Wagtail to get the latest and greatest,
Django to latest version (should silence dependabot)
Pillow in the light of  https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-10379, thanks @kaedroho
=> Upgrade Wagtail to 2.9.2 and Pillow to 7.1.2

wagtailio/images/migrations/0001_initial.py, wagtailio/images/migrations/0005_upgrade_to_wagtail17_schema.py, wagtailio/images/migrations/0006_upgrade_to_wagtail17_data.py
Migration fixes for this issue -> https://github.com/wagtail/wagtail.io/issues/80 
When spinning up this project migrations dont work inside of vagrant. Editing the migration files fixed the problem. I took the solutions from [this thread](https://github.com/wagtail/wagtail/issues/5067) https://github.com/wagtail/wagtail/issues/5067
=> Migration fixes

wagtailio/static/css/components/blog.scss
Apply the following fix to prevent blog-items from showing up on mobile view.
https://github.com/wagtail/wagtail.io/issues/77#issuecomment-730525297
=> Blog items overlapping blog content issue

requirements.txt, wagtailio/utils/blocks.py
=> Wagtail 2.12 upgrade

README.md, requirements.txt
Adds:
* Airtable version bump
* Additional installation instructions with vagrant
=> Small updates

Vagrantfile, Vagrantfile.local.example, vagrant/provision.sh
Bumps VM to wagtail/buster64
related #45
=> Update Vagrant box to buster (parity with production)

requirements.txt
=> Bump AB testing

wagtailio/api.py, wagtailio/areweheadlessyet/models.py, wagtailio/settings/base.py, wagtailio/urls.py
This PR adds Wagtail v2 API configuration.
=> [AreWeHeadlessYet] Configure API

.gitpod.Dockerfile, .gitpod.yml, Dockerfile, Makefile, README.md, docker-compose.yml, fabfile.py, heroku.yml
This PR adds configuration for docker-compose and gitpod.
Looking to get some initial feedback, I'll update the readme and remove Vagrant if everyone is happy with this config.
=> Configuration for docker-compose and gitpod

fabfile.py
=> Update main branch name in fabfile

Dockerfile
To fix the following error: 
```
FileNotFoundError: [Errno 2] No such file or directory: '/app/wagtailio/static_compiled'
The command '/bin/sh -c SECRET_KEY=none django-admin collectstatic --noinput --clear' returned a non-zero code: 1```
=> Fix FE static on build

.stylelintignore, .stylelintrc.js, wagtailio/static/sass/abstracts/_mixins.scss, wagtailio/static/sass/base/_fonts.scss, wagtailio/static/sass/components/_buttons.scss
- Adds rules from https://github.com/wagtail/wagtail/blob/main/.stylelintrc.js
- Ignore vendor dir
- Lint CSS
=> Add stylelint config

wagtailio/project_styleguide/templates/patterns/_pattern_library_only/streamfields.html, wagtailio/project_styleguide/templates/patterns/components/streamfields/cta.html, wagtailio/project_styleguide/templates/patterns/components/streamfields/cta.yaml, wagtailio/static/sass/atoms/icons.scss, wagtailio/static/sass/base/_typography.scss, wagtailio/static/sass/components/_cta.scss, wagtailio/static/sass/main.scss
Available in pattern-library [here](http://0.0.0.0:3000/pattern-library/render-pattern/patterns/components/streamfields/cta.html)
=> Standalone cta

wagtailio/static/sass/components/_standalone-quote.scss
Adds sizing for icon that was missed from the previous MR
=> Standalone quote icon sizing

wagtailio/project_styleguide/templates/patterns/components/streamfields/cards/card_block.html, wagtailio/project_styleguide/templates/patterns/components/streamfields/cards/cards_list_block.html, wagtailio/project_styleguide/templates/patterns/components/streamfields/cards/logo_card_block.html, wagtailio/project_styleguide/templates/patterns/components/streamfields/cards/logo_card_block.yaml, wagtailio/project_styleguide/templates/patterns/components/streamfields/cards/logo_cards_list_block.html, wagtailio/project_styleguide/templates/patterns/components/streamfields/cards/logo_cards_list_block.yaml, wagtailio/static/sass/abstracts/_variables.scss, wagtailio/static/sass/components/_logo-card-grid.scss, wagtailio/static/sass/components/_logo-card.scss, wagtailio/static/sass/main.scss
Adds style for:
- a single logo card - viewable here (http://localhost:8000/pattern-library/render-pattern/patterns/components/streamfields/cards/logo_card_block.html)
- a list of logo cards - [viewable here](http://localhost:8000/pattern-library/render-pattern/patterns/components/streamfields/cards/logo_cards_list_block.html) 
Also:
- Adds base button and list styles
=> Logo cards

wagtailio/project_styleguide/templates/patterns/components/author/author.yaml, wagtailio/project_styleguide/templates/patterns/components/streamfields/comparison_table_block/comparison_table_block.yaml, wagtailio/project_styleguide/templates/patterns/components/streamfields/highlight_block/highlight_block.yaml, wagtailio/project_styleguide/templates/patterns/components/streamfields/quotes/quotes.yaml, wagtailio/project_styleguide/templates/patterns/components/streamfields/quotes/standalone_quote_block.yaml, wagtailio/project_styleguide/templates/patterns/components/streamfields/teaser/teaser.yaml, wagtailio/project_styleguide/templates/patterns/components/streamfields/teaser_block/teaser_block.yaml, wagtailio/project_styleguide/templates/patterns/components/streamfields/text_and_media_block/text_and_media_block.yaml, wagtailio/project_styleguide/templates/patterns/styleguide/streamfields.yaml, wagtailio/project_styleguide/templates/patterns/styleguide/text_and_media_blocks.yaml
Replaces images in the pattern library - `via.placeholder` with `placehold.co`
=> Update placeholder images

wagtailio/project_styleguide/templates/patterns/components/hero/hero.html, wagtailio/project_styleguide/templates/patterns/components/streamfields/cards/logo_card_block.html, wagtailio/project_styleguide/templates/patterns/components/streamfields/cta/cta.html, wagtailio/project_styleguide/templates/patterns/components/streamfields/cta/cta_block.html, wagtailio/project_styleguide/templates/patterns/components/streamfields/quotes/quotes.html, wagtailio/project_styleguide/templates/patterns/components/streamfields/rich_text_block/rich_text_block.html, wagtailio/project_styleguide/templates/patterns/components/streamfields/text_and_media_block/text_and_media_block.html, wagtailio/project_styleguide/templates/patterns/pages/content_page/content_page.html, wagtailio/static/sass/abstracts/_mixins.scss, wagtailio/static/sass/base/_typography.scss, wagtailio/static/sass/components/_buttons.scss, wagtailio/static/sass/components/_cta.scss, wagtailio/static/sass/components/_headline.scss, wagtailio/static/sass/components/_hero.scss, wagtailio/static/sass/components/_highlight.scss, wagtailio/static/sass/components/_icon-bullets.scss, wagtailio/static/sass/components/_icon.scss, wagtailio/static/sass/components/_logo-card-grid.scss, wagtailio/static/sass/components/_quotes.scss, wagtailio/static/sass/components/_rich-text.scss, wagtailio/static/sass/components/_standalone-quote.scss, wagtailio/static/sass/components/_text-media.scss
Some general Streamfield fixes now the content page BE has been done. 
I've added a `sf-spacing` class so the spacing between streamfields should be consistent.
=> Content page

wagtailio/project_styleguide/templates/patterns/components/streamfields/cards/logo_card_block.html, wagtailio/project_styleguide/templates/patterns/components/streamfields/cards/logo_card_block.yaml, wagtailio/project_styleguide/templates/patterns/components/streamfields/cards/logo_cards_list_block.yaml, wagtailio/project_styleguide/templates/patterns/components/streamfields/teaser/teaser.html, wagtailio/project_styleguide/templates/patterns/components/streamfields/text_and_media_block/text_and_media_block.html, wagtailio/project_styleguide/templates/patterns/includes/header.html, wagtailio/static/sass/base/_typography.scss, wagtailio/static/sass/components/_buttons.scss, wagtailio/static/sass/components/_cta.scss, wagtailio/static/sass/components/_headline.scss, wagtailio/static/sass/components/_highlight.scss, wagtailio/static/sass/components/_icon-bullet.scss, wagtailio/static/sass/components/_icon-link.scss, wagtailio/static/sass/components/_logo-card.scss, wagtailio/static/sass/components/_meta.scss, wagtailio/static/sass/components/_quotes.scss, wagtailio/static/sass/components/_responsive-object.scss, wagtailio/static/sass/components/_teaser.scss, wagtailio/static/sass/components/_text-media.scss, wagtailio/static/sass/layout/_header.scss, wagtailio/static/sass/main.scss
Address feedback that was covered in the 1st design review session. The spreadsheet is linked from the ticket containing the feedback.
Edit: The mobile search feedback will be covered in its own ticket as Ben was doing a mock up for it.
=> Design review feedback

wagtailio/project_styleguide/templates/patterns/includes/footer.yaml, wagtailio/project_styleguide/templates/patterns/includes/menu_footer.html, wagtailio/static/sass/components/_footer-menu.scss, wagtailio/static/sass/components/_icon-bullet.scss, wagtailio/static/sass/components/_icon.scss, wagtailio/static/sass/components/_quotes.scss, wagtailio/static/sass/components/_rich-text.scss
- Change rich text position to outside and add left space
- Icon bullet only spans 3 columns at large breakpoint
- Make icons a percentage stroke width so they're all even
- Ensure quote icon doesn't allow page to be scrolled horizontally
=> Demo fixes

wagtailio/core/templates/core/home_page.html, wagtailio/project_styleguide/templates/patterns/base.html, wagtailio/project_styleguide/templates/patterns/base_page.html, wagtailio/project_styleguide/templates/patterns/includes/header.html, wagtailio/static/sass/layout/_header.scss
Adds Github star count button viewable on the homepage locally
=> GitHub star button

wagtailio/static/sass/components/_footer-menu.scss, wagtailio/static/sass/layout/_footer.scss
Match footer menu and credit font sizes to design
=> Footer font sizes

wagtailio/project_styleguide/templates/patterns/components/streamfields/comparison_table_block/comparison_table_block.html, wagtailio/static/sass/components/_comparison-table.scss, wagtailio/static/sass/components/_grid.scss
Allow for scrolling tables on mobile
=> Mobile table scroll

wagtailio/static/sass/components/_grid.scss
add spacing under table on mobile
=> Table spacing

wagtailio/static/sass/components/_feature.scss
Ensure the minus and plus icons show when a feature is collapsed or open
=> Fix Feature Icons

wagtailio/settings/base.py
The Preview function is not working because it is asking for credentials and will not accept the default password
=> Bugfix for broken wagtail admin page previews

wagtailio/project_styleguide/templates/patterns/components/buttons/button.html
Ticket: #73
Adding a conditional around the button to ensure it only displays when a url is provided
=> Make sure that the button components has a url

README.md
Simple update to add `make migrate` to the readme
=> Adding make migrate to readme file

fabfile.py
- This is a small update to the `fabfile.py`. 
- Builds up on work done in #268 and 7cef2d8c7b60b01a4223c41c38429c95de554091
**Note**: No related Monday tickets
=> Update LOCAL_DATABASE_NAME from wagtailio to wagtailorg

wagtailio/static/sass/components/_buttons.scss
<details>
[`#80d7d8` on `#ffffff`: fail](https://webaim.org/resources/contrastchecker/?fcolor=80D7D8&bcolor=FFFFFF)
**On hover**
[`#80d7d8` on `#2e1f5e`: pass](https://webaim.org/resources/contrastchecker/?fcolor=80D7D8&bcolor=2E1F5E)
[`#80d7d8` on `#000000`: pass](https://webaim.org/resources/contrastchecker/?fcolor=80D7D8&bcolor=000000)
**On hover**
[`#80d7d8` on `#ffffff`: fail](https://webaim.org/resources/contrastchecker/?fcolor=80D7D8&bcolor=FFFFFF)
</details>
<details>
[`#007d7e` on `#ffffff`: pass](https://webaim.org/resources/contrastchecker/?fcolor=007d7e&bcolor=FFFFFF)
**On hover**
[`#80d7d8` on `#2e1f5e`: pass](https://webaim.org/resources/contrastchecker/?fcolor=80D7D8&bcolor=2E1F5E)
[`#80d7d8` on `#000000`: pass](https://webaim.org/resources/contrastchecker/?fcolor=80D7D8&bco …
=> Fix button arrow icon colour contrast

wagtailio/blog/models.py
=> Add author search by name

wagtailio/project_styleguide/templates/patterns/components/streamfields/looping_video_block/looping_video_block.html, wagtailio/project_styleguide/templates/patterns/pages/home/home_page.html, wagtailio/services/templates/services/blocks/section.html, wagtailio/static/js/components/looping-video.js, wagtailio/static/js/main.js
This PR adds the ability to pause and play autoplaying videos by clicking them or focusing on them and pressing <kbd>Space</kbd> or <kbd>Enter</kbd>. If the user prefers reduced motion, the video will be immediately paused.
TODO: show play/pause button on hover?
=> Allow pausing/playing video by clicking or using keyboard

wagtailio/project_styleguide/templates/patterns/pages/home/home_page.html
Very tiny fix to make sure our title includes "CMS" for keyword searches.
=> Minor SEO fix.

wagtailio/project_styleguide/templates/patterns/base_page.html
Note: did not remove the css or the clipboard icon, but could do that too if needed
=> Remove footer survey link

poetry.lock
=> Upgrade Wagtail to 4.1.1

wagtailio/settings/base.py
=> Drop trailaing slash from `WAGTAILADMIN_BASE_URL`

wagtailio/newsletter/models.py, wagtailio/project_styleguide/templates/patterns/base.html
Just adding a couple of Wagtail 4 considerations that I noticed are missing.
=> Wagtail 4 considerations

SECURITY.md, public/.well-known/security.txt, wagtailio/settings/base.py
See also https://github.com/wagtail/wagtail/pull/9751
=> Add security.txt

wagtailio/project_styleguide/templates/patterns/components/sign_up_form/sign_up_form.yaml, wagtailio/project_styleguide/templates/patterns/includes/footer.html
This PR includes a small text correction to fix a long-standing error in the footer of Wagtail.org. We have had the incorrect title for our newsletter for a while now and this PR is needed to correct the title because they are hard-coded into the site.
=> Updating Newsletter title

.gitignore, Dockerfile, Makefile, README.md, docker-compose.yml, fabfile.py, poetry.lock, pyproject.toml, vagrant/provision.sh
Replaces https://github.com/wagtail/wagtail.org/pull/389
- Remove the need for AWS / Heroku CLIs - this is now all done locally, outside the container / VM
- Remove the ability to push data to production / staging - this is almost always a bad idea
- Stop using a fork of fabric - use the host version
- Remove `make` wrappers around fab commands
- Automate deployment for branches
=> Fix Docker build issues and refactor Fabfile

wagtailio/static/sass/components/_nav-cta.scss
=> fixing hover colour on light mode dropdowns

docs/data_protection.md, docs/deployment.md, docs/infrastructure.md
This is based on internal project templates. I’ve updated all the content to not have any erroneous information, but there might be more to add.
=> Add infrastructure and data protection documentation

Dockerfile
Fixes warnings when building the images
https://docs.docker.com/reference/build-checks/from-as-casing/
=> Fix inconsistent FROM vs AS casing

wagtailio/project_styleguide/templates/patterns/base_page.html, wagtailio/static/sass/abstracts/_variables.scss, wagtailio/static/sass/layout/_space-page.scss
Rather than using #545 to advertise Wagtail Space, I've created a banner using conditional template logic instead. The advantages of this approach are that we get to use images in the design and that the banner loads at the same time as the rest of the content on the page. The downsides are that it must be edited within the code base and we will have to remove this banner or comment it out in the code after Wagtail Space is over.
Any feedback or suggestions on this approach would be much appreciated!
=> Wagtail Space Banner w/Conditional Template Logic

wagtailio/project_styleguide/templates/patterns/includes/spaceheader.html, wagtailio/project_styleguide/templates/patterns/pages/space_schedule_page/space_schedule_page.html
Turns out there is a popup in the Pretalx widget that was behaving weirdly because of our styling. Adding an inline-style to the widget corrected the issue.
=> Space widget hotfix
